---
platform: linux

image_resource:
  type: docker-image
  source: {repository: python}

inputs:
  - name: kindle-highlights-gitrepo

run:
  path: bash
  args:
    - -c
    - |
      ls -lrth
      python3 kindle-highlights-gitrepo/main.py
